apiVersion: apps/v1
kind: Deployment
metadata:
  name: statec-rest-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statec-rest-api
  template:
    metadata:
      labels:
        app: statec-rest-api
    spec:
      containers:
      - name: statec-rest-api
        image: statec-rest-api
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: statec-rest-api-service
spec:
  selector:
    app: statec-rest-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort