apiVersion: v1
kind: Service
metadata:
  name: statec-rest-api-service
  labels:
    app: statec-rest-api
spec:
  selector:
    app: statec-rest-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer   
